theme: jekyll-theme-architect
# https://github.com/pages-themes/architect
title: "Bremer Windsurfing-Club"
#description: [A short description of your site's purpose]
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

